default:
	@echo -- show help ----------------------------------------
	python greeting.py -h
	@echo -- run command ----------------------------------------
	python greeting.py --is-surprised hello
	@echo -- using config.json -----------------------------------
	cat ./config.json
	python greeting.py --config=file://config.json hello
